trigger:
- master
# Only run this pipeline on a Pull Request if this file is modified; the rest
# is all for azure-pipelines-linux to handle.
pr:
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines-windows.yml

jobs:
- job: WindowsDependencies
  displayName: 'Windows Dependencies'
  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  - script: |
      cd /d c:\vcpkg
      git pull
      .\bootstrap-vcpkg.bat
    displayName: 'Update vcpkg'
  - script: vcpkg.exe install freetype:x64-windows-static liblzma:x64-windows-static libpng:x64-windows-static lzo:x64-windows-static zlib:x64-windows-static
    displayName: 'Install x64 dependencies'
  - script: vcpkg.exe install freetype:x86-windows-static liblzma:x86-windows-static libpng:x86-windows-static lzo:x86-windows-static zlib:x86-windows-static
    displayName: 'Install x86 dependencies'
  - bash: |
      set -ex

      rm -rf /c/vcpkg/.git*
      rm -rf /c/vcpkg/buildtrees
      rm -rf /c/vcpkg/docs
      rm -rf /c/vcpkg/downloads
      rm -rf /c/vcpkg/packages
      rm -rf /c/vcpkg/ports
      rm -rf /c/vcpkg/toolsrc
      mv /c/vcpkg windows-dependencies
    displayName: 'Remove unused files'
  - task: ArchiveFiles@2
    displayName: Archive
    inputs:
      rootFolderOrFile: 'windows-dependencies'
      archiveFile: 'windows-dependencies.zip'

  # Only publish when it triggered on 'master' (and not on a Pull Request)
  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish
    inputs:
      PathtoPublish: windows-dependencies.zip
      ArtifactName: 'windows-dependencies'
