FROM debian:stretch

LABEL \
        org.label-schema.description="OpenTTD Compile-Farm image to produce binaries for specific target" \
        org.label-schema.schema-version="1.0" \
        org.label-schema.url="https://www.openttd.org/" \
        org.label-schema.vendor=OpenTTD

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workdir/source

ENTRYPOINT ["release.sh"]
CMD ["dev"]

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
	build-essential \
	ca-certificates \
	git \
	mercurial \
	patch \
	pkg-config \
	subversion \
	zip \
	wget \
	&& rm -rf /var/lib/apt/lists/*

RUN cd / && git clone https://github.com/tpoechtrager/osxcross.git
RUN apt-get update \
	&& cd /osxcross \
	&& tools/get_dependencies.sh \
	&& apt-get install -y --no-install-recommends cmake \
	&& rm -rf /var/lib/apt/lists/*
RUN cd /osxcross/tarballs \
	&& wget @OSXSDKURL@/osx-sdk/MacOSX@RELEASE@.sdk.tar.xz

# osxcross-macports expects --i386 for i386, and otherwise nothing.
# It overwrites ARCH.
# This is hard to create in a Dockerfile, so we modify the file a bit to make it easier for us.
RUN sed -i 's/ARCH="x86_64"//' /osxcross/tools/osxcross-macports

# Build osxcross, and fix up permissions of the SDK; this has to be done in one step, as AUFS otherwise fails to allow non-root to read the SDK
RUN cd /osxcross && OSX_VERSION_MIN=@RELEASE@ UNATTENDED=1 ./build.sh \
	&& chown -R root:root /osxcross/target/SDK \
	&& find /osxcross/target/SDK -type d -exec chmod 0755 {} \;

# Only OSX 10.7+ supports compiler-RT; currently fails to compile
#RUN cd /osxcross && if [ "@RELEASE@" != "10.6" ]; then ./build_compiler_rt.sh; fi

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/osxcross/target/bin
ENV MACOSX_DEPLOYMENT_TARGET=@RELEASE@

# Only install static libraries, so we never link to the dylib
RUN OSXCROSS_MACPORTS_MIRROR="http://packages.macports.org" ARCH=@ARCH@ osxcross-macports --static install \
	freetype \
	icu \
	libpng \
	lzo2 \
	zlib \
	xz

# Allow easy access to macports
RUN ln -s /osxcross/target/macports/pkgs/opt/local /opt/local
# Make sure we have a "sysroot"
RUN ln -s /osxcross/target/SDK/MacOSX@RELEASE@.sdk/System /System

ENV CC=cc
ENV CXX=c++

ADD release.sh /usr/bin/
