FROM debian:stretch

LABEL \
	org.label-schema.description="OpenTTD Compile-Farm image to produce source bundles and documentation" \
	org.label-schema.schema-version="1.0" \
	org.label-schema.url="https://www.openttd.org/" \
	org.label-schema.vendor=OpenTTD

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
	build-essential \
	doxygen \
	gawk \
	ghostscript \
	git \
	mercurial \
	patch \
	rsync \
	subversion \
	texlive \
	zip \
	&& rm -rf /var/lib/apt/lists/*

COPY release.sh /usr/bin/

WORKDIR /workdir/source

ENTRYPOINT ["release.sh"]
CMD ["dev"]
