#!/bin/sh

set -e

. $(realpath $(dirname ${0}))/../../linux-base-image.source

ARCH=${DOCKER_TAG}
if [ "${ARCH}" != "amd64" ]; then
    DISTRO="${ARCH}/${DISTRO}"
fi
if [ "${DISTRO}" = "debian" ]; then
    BASE_IMAGE="${BASE_IMAGE}-slim"
fi

DOCKER_OPTS=${DOCKER_OPTS:-}

echo "Building docker image based on ${DISTRO}:${BASE_IMAGE} .."

docker build \
    ${DOCKER_OPTS} \
    --build-arg DISTRO=${DISTRO} \
    --build-arg BASE_IMAGE=${BASE_IMAGE} \
    -t ${IMAGE_NAME} \
    .

